services:
  cardb:
    container_name: $DB_HOST
    image: postgres:16
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - PGUSER=$DB_USER
      - PGPORT=$DB_PORT
    volumes:
      - car-data:/var/lib/postgres/data
      - car-database.conf:/var/lib/postgres/data/postgresql.conf
    ports:
      - 5433:$DB_PORT
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
        interval: 3s
        timeout: 5s
        retries: 5

  ml:
    container_name: $ML_HOST
    depends_on:
      - cardb
    build:
      context: ml-service
      dockerfile: Dockerfile
    ports:
      - $ML_PORT:$ML_PORT

  translate:
    container_name: $TR_HOST
    image: libretranslate/libretranslate
    environment:
      - LT_LOAD_ONLY=en,ru
      - LT_PORT=$TR_PORT
    ports:
      - $TR_PORT:$TR_PORT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://$HOST:$TR_PORT"]

  gateway:
    container_name: $GW_HOST
    depends_on:
      - translate
    build:
      context: gateway-service
      dockerfile: Dockerfile
    ports:
      - $GW_PORT:$GW_PORT

  # client:
  #   build:
  #     context: client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000


volumes:
  car-data:
  car-database.conf: