services:
  database:
    image: postgres:16
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - car-data:/var/lib/postgres/data
      - car-database.conf:/var/lib/postgres/data/postgresql.conf
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - PGUSER=$DB_USER
      - PGPORT=$DB_PORT
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
        interval: 3s
        timeout: 5s
        retries: 5

  ml_service:
    depends_on:
      - database
    build:
      context: ml-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  ml_service:
    depends_on:
      - database
    build:
      context: ml-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000


volumes:
  gogame-data:
  gogame-database.conf:
  gogame-cache:
  gogame-cache.conf:

# // docker run -e LT_LOAD_ONLY="en,ru" -ti --rm -p 5000:5000 libretranslate/libretranslate